language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: nightly
    - php: hhvm

addons:
  code_climate:
    repo_token: 51bd5ca279df15b4dd19f98bb45d4823e6cb117118208330f38ef97aa902843d

before_install:
 - gem install sass
 - npm install less
 - npm install coffee-script

install: composer install

after_script:
  - vendor/bin/test-reporter